CREATE TABLE TBUSUARIO (
	USUCODIGO SERIAL NOT NULL,
	USUNOME VARCHAR(256) NOT NULL,
	USUEMAIL VARCHAR(256) NOT NULL,
	USUSENHA VARCHAR(256) NOT NULL
);

ALTER TABLE TBUSUARIO ADD CONSTRAINT pk_tbusuario
PRIMARY KEY (usucodigo);

CREATE TABLE TBPERGUNTA(
	PERCODIGO SERIAL NOT NULL,
	PERDESCRICAO VARCHAR(256) NOT NULL
);

ALTER TABLE TBPERGUNTA ADD CONSTRAINT pk_tbpergunta
PRIMARY KEY (percodigo);

CREATE TABLE TBRESPOSTA(
	USUCODIGO INTEGER NOT NULL,
	PERCODIGO INTEGER NOT NULL,	
	RESALTERNATIVA VARCHAR(256) NOT NULL
);

ALTER TABLE TBRESPOSTA ADD CONSTRAINT pk_tbresposta
PRIMARY KEY (usucodigo, percodigo);

ALTER TABLE TBRESPOSTA ADD CONSTRAINT "FK TBRESPOSTA -> TBUSUARIO"
FOREIGN KEY(USUCODIGO)
REFERENCES TBUSUARIO(USUCODIGO);

ALTER TABLE TBRESPOSTA ADD CONSTRAINT "FK TBRESPOSTA -> TBPERGUNTA"
FOREIGN KEY(PERCODIGO)
REFERENCES TBPERGUNTA(PERCODIGO);